import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils"
import Navbar from "@/components/navbar";
import { AOSInit } from "@/lib/AOSInit";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body  className={cn(
          "font-sans overflow-x-hidden antialiased",
          fontSans.variable
        )}>
          <AOSInit/>
          <Navbar />
          {children}</body>
    </html>
  );
}
