import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils"
import Navbar from "@/components/navbar";
import { AOSInit } from "@/lib/AOSInit";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body  className={cn(
          "font-sans antialiased",
          fontSans.variable
        )}>
          <AOSInit/>
          <Navbar />
          <div 
    className=" w-full dark:bg-black bg-[#ffe8d3]  dark:bg-grid-white/[0.2] bg-grid-black/[0.2] relative flex items-center justify-center">
         <div className="absolute pointer-events-none inset-0 flex items-center justify-center dark:bg-black bg-white [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]"></div>
          {children}
       </div>
          </body>
    </html>
  );
}
